config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :vibrations, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :revibrations, only: [:create, :destroy]
    resources :reply_vibrations, only: :create
  end

  resources :bookmarks, only: :index

  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :usernames, only: [:new, :update]

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :hashtags, only: [:index, :show], path: "/explore"

  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end

  resources :messages, only: :create

  resources :notifications, only: [:index, :destroy]

  get "/vibration_polling", to: "vibration_polling#index"
end

app/models/vibration.rb
class Vibration < ApplicationRecord
  HASHTAG_REGEX = /(#\w+)/

  belongs_to :user

  validates :body, presence: true, length: { maximum: 280 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :revibrations, dependent: :destroy
  has_many :revibrationed_users, through: :revibrations, source: :user
  has_many :views, dependent: :destroy
  has_many :viewed_users, through: :views, source: :user
  has_and_belongs_to_many :hashtags
  belongs_to :parent_vibration,
             inverse_of: :reply_vibrations,
             foreign_key: :parent_vibration_id,
             class_name: "Vibration",
             optional: true,
             counter_cache: :reply_vibrations_count
  has_many :reply_vibrations, foreign_key: :parent_vibration_id, class_name: "Vibration"
  has_many :mentions, dependent: :destroy
  has_many :mentioned_users, through: :mentions

  before_save :parse_and_save_hashtags
  def parse_and_save_hashtags
    matches = body.scan(HASHTAG_REGEX)
    return if matches.empty?

    matches.flatten.each do |tag|
      hashtag = Hashtag.find_or_create_by(tag: tag.delete("#"))
      hashtags << Hashtag.find_or_create_by(tag: tag.delete("#"))
    end
  end

  after_save :parse_and_save_mentions
  def parse_and_save_mentions
    matches = body.scan(/(@\w+)/)
    return if matches.empty?

    matches.flatten.each do |mention|
      mentioned_user = User.find_by(username: mention.delete("@"))
      next if mentioned_user.blank?

      next if mentions.exists?(mentioned_user: mentioned_user)

      mentions.create(mentioned_user: mentioned_user)
      Notification.create(user: mentioned_user, actor: user, verb: "mentioned-me")
      mentions.find_or_create_by(mentioned_user: mentioned_user)
    end
  end
end

app/controllers/vibrations_controller.rb
class VibrationsController < ApplicationController
  before_action :authenticate_user!

  def show
    ViewVibrationJob.perform_later(vibration: vibration, user: current_user)
    @vibration_presenter = VibrationPresenter.new(vibration: vibration, current_user: current_user)
    @reply_vibrations_in_presenter = vibration.reply_vibrations.includes(
      :liked_users, :bookmarked_users, :revibrationed_users, :user
    ).order(created_at: :desc).map do |reply_vibration|
      VibrationPresenter.new(vibration: reply_vibration, current_user: current_user)
    end
  end

  def create
    @vibration = Vibration.create(vibration_params.merge(user: current_user))
    VibrationActivity::VibrationedJob.perform_later(actor: current_user, vibration: @vibration)

    if @vibration.persisted?
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.turbo_stream
      end
    end
  end

  private

  def vibration_params
    params.require(:vibration).permit(:body)
  end

  def vibration
    @vibration ||= Vibration.find(params[:id])
  end
end

app/views/vibrations/_show_stats.html.erb
<div id="vibration_stats">
  <div class="d-flex justify-content-start mb-4">
    <div class="me-4"><span class="fw-bold"><%= vibration_presenter.views_count %></span> Views</div>
    <div class="me-4"><span class="fw-bold"><%= vibration_presenter.reply_vibrations_count %></span> Replies</div>
    <div class="me-4"><span class="fw-bold"><%= vibration_presenter.revibrations_count %></span> Revibrations</div>
    <div class="me-4"><span class="fw-bold"><%= vibration_presenter.likes_count %></span> Likes</div>
  </div>

  <div class="d-flex justify-content-evenly align-items-center action-links">
    <div>
      <%= link_to "#", class: "text-decoration-none text-black views" do %>
        <%= image_tag "bar-graph.png", size: "24x24", class: "me-1" %>
      <% end %>
    </div>
    <div>
      <%= link_to vibration_path(vibration_presenter.vibration), class: "text-decoration-none text-black replies" do %>
        <%= image_tag "speech-bubble.png", size: "24x24", class: "me-1" %>
      <% end %>
    </div>
    <div>
      <%= link_to vibration_presenter.revibration_vibration_url(source: "vibration_show"), data: { "turbo-method": vibration_presenter.turbo_revibration_data_method }, class: "text-decoration-none text-black revibrations" do %>
        <%= image_tag vibration_presenter.revibration_image, size: "24x24", class: "me-1" %>
      <% end %>
    </div>
    <div>
      <%= link_to vibration_presenter.like_vibration_url(source: "vibration_show"), data: { "turbo-method": vibration_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
        <%= image_tag vibration_presenter.like_heart_image, size: "24x24", class: "me-1" %>
      <% end %>
    </div>
    <div>
      <%= link_to vibration_presenter.bookmark_vibration_url(source: "vibration_show"), data: { "turbo-method": vibration_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmark" do %>
        <%= image_tag vibration_presenter.bookmark_image, size: "24x24", class: "me-1" %>
      <% end %>
    </div>
  </div>
</div>

app/views/vibrations/_vibration.html.erb
<%= vibration_presenter.vibration_activity_html.html_safe %>
<%= turbo_frame_tag dom_id(vibration_presenter.vibration) do %>
  <div data-controller="vibration-card" data-vibration-path="<%= vibration_path(vibration_presenter.vibration) %>" class="vibration hover d-flex py-3 px-3">
    <div class="flex-shrink-0">
      <%= link_to user_path(vibration_presenter.user) do %>
        <%= image_tag vibration_presenter.avatar, size: "48x48", class: "rounded-circle" %>
      <% end %>
    </div>
    <div class="flex-grow-1 ms-3">
      <p class="mb-0">
        <span class="fw-bolder"><%= vibration_presenter.display_name %></span>
        <span class="text-muted">
          @<%= vibration_presenter.username %> · <%= vibration_presenter.created_at %></span>
      </p>
      <%= vibration_presenter.body_html.html_safe %>

      <div class="d-flex justify-content-between align-items-center action-links">
        <div>
          <%= link_to vibration_path(vibration_presenter.vibration), data: { "ignore-click": true }, class: "text-decoration-none text-black views" do %>
            <%= image_tag "bar-graph.png", size: "20x20", class: "me-1" %>
            <span><%= vibration_presenter.views_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to vibration_path(vibration_presenter.vibration), data: { "ignore-click": true }, class: "text-decoration-none text-black replies" do %>
            <%= image_tag "speech-bubble.png", size: "20x20", class: "me-1" %>
            <span><%= vibration_presenter.reply_vibrations_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to vibration_presenter.revibration_vibration_url, data: { "ignore-click": true, "turbo-method": vibration_presenter.turbo_revibration_data_method }, class: "text-decoration-none text-black revibrations" do %>
            <%= image_tag vibration_presenter.revibration_image, size: "20x20", class: "me-1" %>
            <span><%= vibration_presenter.revibrations_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to vibration_presenter.like_vibration_url, data: { "ignore-click": true, "turbo-method": vibration_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do %>
            <%= image_tag vibration_presenter.like_heart_image, size: "20x20", class: "me-1" %>
            <span><%= vibration_presenter.likes_count %></span>
          <% end %>
        </div>
        <div>
          <%= link_to vibration_presenter.bookmark_vibration_url, data: { "ignore-click": true, "turbo-method": vibration_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black bookmark" do %>
            <%= image_tag vibration_presenter.bookmark_image, size: "20x20", class: "me-1" %>
            <span><%= vibration_presenter.bookmark_text %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/vibrations/create.turbo_stream.erb
<%= turbo_stream.prepend "vibrations" do %>
  <%= render partial: "vibrations/vibration", locals: { vibration_presenter: VibrationPresenter.new(vibration: @vibration, current_user: current_user) } %>
<% end %>

app/views/vibrations/show.html.erb
<div class="col-7">
  <div class="mb-3">
    <%= link_to :back, class: "fs-4 text-decoration-none text-black fw-semibold" do %>
      <%= image_tag "back-arrow.png", size: "28x28", class: "me-4" %>
      <span style="position: relative; top: 2px;">Vibration</span>
    <% end %>

    <div data-vibration-path="<%= vibration_path(@vibration_presenter.vibration) %>" class="vibration d-flex py-3 px-3">
      <div class="flex-shrink-0">
        <%= link_to user_path(@vibration_presenter.user) do %>
          <%= image_tag @vibration_presenter.avatar, size: "48x48", class: "rounded-circle" %>
        <% end %>
      </div>
      <div class="flex-grow-1 ms-3">
        <p class="fw-bolder mb-0"><%= @vibration_presenter.display_name %></p>
        <p class="text-muted mb-1">@<%= @vibration_presenter.username %></p>
        <%= @vibration_presenter.body_html(p_class: "fs-2 mb-1").html_safe %>
        <p class="text-muted"><%= @vibration_presenter.vibration.created_at.strftime("%l:%M %p") %> · <%= @vibration_presenter.vibration.created_at.strftime("%b %d, %Y") %></p>

        <%= render "show_stats", vibration_presenter: @vibration_presenter %>
      </div>
    </div>
  </div>

  <%= render "shared/vibration_form", form_submit_path: vibration_reply_vibrations_path(@vibration_presenter.vibration), button_label: "Reply" %>

  <div id="reply_vibrations">
    <%= render partial: "vibrations/vibration", collection: @reply_vibrations_in_presenter, as: :vibration_presenter %>
  </div>
</div>
<div class="col">
  Column
</div>