config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :vibrations, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :revibrations, only: [:create, :destroy]
    resources :reply_vibrations, only: :create
  end

  resources :bookmarks, only: :index

  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :usernames, only: [:new, :update]

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :hashtags, only: [:index, :show], path: "/explore"

  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end

  resources :messages, only: :create

  resources :notifications, only: [:index, :destroy]

  get "/vibration_polling", to: "vibration_polling#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :actor, class_name: "User"
  belongs_to :vibration, optional: true

  VERBS = %w[followed-me liked-vibration mentioned-me].freeze

  VERBS.each do |v|
    define_method("#{v.gsub("-", "_")}?") { v == verb }
  end
  validates :verb, presence: true, inclusion: { in: VERBS }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.includes(:actor, :vibration)
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/views/notifications/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@notification) %>

app/views/notifications/index.html.erb
<div class="col-7">
  <div class="mb-3">
    <%= link_to "Notifications", notifications_path, class: "fs-4 text-decoration-none text-black fw-semibold" %>
  </div>
  <div id="vibrations">
    <% @notifications.each do |notification| %>
      <% if notification.followed_me? %>
        <%= turbo_frame_tag dom_id(notification) do %>
          <div class="notification d-flex justify-content-between py-2 px-3">
            <div>
              <% if notification.actor.avatar.present? %>
                <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle" %>
              <% else %>
                <%= image_tag "user.png", size: "48x48", class: "rounded-circle" %>
              <% end %>
              <p class="mb-1"><span class="fw-bold"><%= notification.actor.display_name %></span> followed you</p>
            </div>
            <div>
              <%= link_to "", notification_path(notification), data: { "turbo-method": :delete }, class: "d-block btn-close" %>
            </div>
          </div>
        <% end %>
      <% elsif notification.liked_vibration? %>
        <%= turbo_frame_tag dom_id(notification) do %>
          <div class="notification d-flex justify-content-between py-2 px-3">
            <div>
              <% if notification.actor.avatar.present? %>
                <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle" %>
              <% else %>
                <%= image_tag "user.png", size: "48x48", class: "rounded-circle" %>
              <% end %>
              <p class="mb-1"><span class="fw-bold"><%= notification.actor.display_name %></span> liked your vibration</p>
              <p class="text-muted mb-1"><%= notification.vibration.body %></p>
              <%= link_to "Show all", vibration_path(notification.vibration), class: "vibration-link mb-1" %>
            </div>
            <div>
              <%= link_to "", notification_path(notification), data: { "turbo-method": :delete }, class: "d-block btn-close" %>
            </div>
          </div>
        <% end %>
      <% elsif notification.mentioned_me? %>
        <%= turbo_frame_tag dom_id(notification) do %>
          <div class="notification d-flex justify-content-between py-2 px-3">
            <div>
              <% if notification.actor.avatar.present? %>
                <%= image_tag notification.actor.avatar, size: "48x48", class: "rounded-circle" %>
              <% else %>
                <%= image_tag "user.png", size: "48x48", class: "rounded-circle" %>
              <% end %>
              <p class="mb-1"><span class="fw-bold"><%= notification.actor.display_name %></span> mentioned you</p>
              <%= link_to "Show @#{notification.actor.username}", user_path(notification.actor), class: "vibration-link mb-1" %>
            </div>
            <div>
              <%= link_to "", notification_path(notification), data: { "turbo-method": :delete }, class: "d-block btn-close" %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="col">
  <%= render "shared/hashtag_sidebar" %>
</div>