config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :vibrations, only: [:show, :create] do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :revibrations, only: [:create, :destroy]
    resources :reply_vibrations, only: :create
  end

  resources :bookmarks, only: :index

  get :dashboard, to: "dashboard#index"
  get :profile, to: "profile#show"
  put :profile, to: "profile#update"

  resources :usernames, only: [:new, :update]

  resources :users, only: :show do
    resources :followings, only: [:create, :destroy]
  end

  resources :hashtags, only: [:index, :show], path: "/explore"

  resources :message_threads, only: :index, path: "/messages" do
    resources :messages, only: :index
  end

  resources :messages, only: :create

  resources :notifications, only: [:index, :destroy]

  get "/vibration_polling", to: "vibration_polling#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show rounded-0 text-center" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_hashtag_sidebar.html.erb
<div class="hashtag-sidebar rounded p-2">
  <p class="p-2 fs-4 mb-0 fw-bold">What's happening?</p>
  <% Hashtag.limit(5).each do |hashtag| %>
    <div class="item p-2" data-controller="hashtag" data-url="<%= hashtag_path(hashtag) %>">
      <p class="fw-bold mb-0 fs-5">#<%= hashtag.tag %></p>
      <p class="text-muted fs-6 mb-0"><%= hashtag.vibrations.size %> Vibrations</p>
    </div>
  <% end %>
  <%= link_to "Show more", hashtags_path, class: "social-link p-2" %>
</div>

app/views/shared/_sidebar.html.erb
<aside class="col side-navbar">
  <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 px-3 mb-3" do %>
    <div class="px-2 py-2 rounded-circle">
      <%= image_tag "social.png", width: "32" %>
    </div>
  <% end %>
  <%= link_to dashboard_path, class: "d-flex align-items-center fs-5 mb-3  #{nav_link_active?('dashboard')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "home.png", width: "32" %></span>
      Home
    </div>
  <% end %>
  <%= link_to hashtags_path, class: "d-flex align-items-center fs-5 mb-3 #{nav_link_active?('hashtags')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "hashtag.png", width: "32" %></span>
      Explore
    </div>
  <% end %>
  <%= link_to notifications_path, class: "d-flex align-items-center fs-5 mb-3 #{nav_link_active?('notifications')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "notifications.png", width: "32" %></span>
      Notifications
    </div>
  <% end %>
  <%= link_to message_threads_path, class: "d-flex align-items-center fs-5 mb-3 #{nav_link_active?('message_threads')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "messages.png", width: "32" %></span>
      Messages
    </div>
  <% end %>
  <%= link_to bookmarks_path, class: "d-flex align-items-center fs-5 mb-3 #{nav_link_active?('bookmarks')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "bookmark-white.png", width: "32" %></span>
      Bookmarks
    </div>
  <% end %>
  <%= link_to profile_path, class: "d-flex align-items-center fs-5 mb-4  #{nav_link_active?('profile')}" do %>
    <div class="px-4 py-2 rounded-pill">
      <span class="me-4 position-relative" style="bottom: 3px;"><%= image_tag "profile.png", width: "32" %></span>
      Profile
    </div>
  <% end %>

  <div class="d-flex align-items-center fs-4 px-4 mb-3">
    <%= button_tag "Vibration", class: "btn btn-lg btn-social w-100 rounded-pill", data: { "bs-toggle": "modal", "bs-target": "#vibration-modal" } %>
  </div>

  <div class="d-flex align-items-center fs-6 px-4">
    <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "social-link" %>
  </div>
</aside>

<!-- Vibration Form Modal -->
<div class="modal" id="vibration-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-bottom-0">
        <button type="button" class="btn-close mx-0 close-modal-btn" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "shared/vibration_form", form_submit_path: vibrations_path, button_label: "Vibration" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_vibration_form.html.erb
<div class="vibration hover d-flex py-3 px-3">
  <div class="flex-shrink-0">
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, size: "48x48", class: "rounded-circle" %>
    <% else %>
      <%= image_tag "user.png", size: "48x48", class: "rounded-circle" %>
    <% end %>
  </div>
  <div class="flex-grow-1 ms-3">
    <%= form_with model: Vibration.new, url: form_submit_path, method: :post, class: "w-100", data: { controller: 'vibration-form' } do |f| %>
      <%= f.text_area :body, placeholder: "What's happening?", class: "form-control w-100 vibration-input mb-4" %>
      <div class="d-flex justify-content-end">
        <%= f.submit button_label, class: "btn btn-lg btn-social rounded-pill" %>
      </div>
    <% end %>
  </div>
</div>